// Generated by `npm run catalog-sites:generate`. Do not edit by hand.
//
// Upstream: neodb-social/neodb@811753c71dc16b51aa979a845eb8a3cb81f384f9 — neodb/catalog/sites/
// 49 sites, 95 patterns, in NeoDB's registration order:
// the first site whose pattern matches a URL is the one that handles it.
//
// `patterns` are the site's URL_PATTERNS. `fallbackPatterns` are the
// pattern-shaped part of what the sites that override `validate_url_fallback`
// start from; NeoDB only consults those when no site matched above.

export type CatalogSiteRule = {
  idType: string;
  siteName: string;
  patterns: string[];
  fallbackPatterns?: string[];
};

export const CATALOG_SITE_RULES: CatalogSiteRule[] = [
  // AniListAnime — AniList (anilist.py)
  {
    idType: "AniList_Anime",
    siteName: "AniList",
    patterns: [
      "\\w+://anilist\\.co/anime/(\\d+)",
    ],
  },
  // AniListManga — AniList (anilist.py)
  {
    idType: "AniList_Manga",
    siteName: "AniList",
    patterns: [
      "\\w+://anilist\\.co/manga/(\\d+)",
    ],
  },
  // ArchiveOfOurOwn — AO3 (ao3.py)
  {
    idType: "AO3",
    siteName: "AO3",
    patterns: [
      "\\w+://archiveofourown\\.org/works/(\\d+)",
    ],
  },
  // AppleMusic — AppleMusic (apple_music.py)
  {
    idType: "AppleMusic",
    siteName: "AppleMusic",
    patterns: [
      "https://music\\.apple\\.com/[a-z]{2}/album/[\\w%-]+/(\\d+)",
      "https://music\\.apple\\.com/[a-z]{2}/album/(\\d+)",
      "https://music\\.apple\\.com/album/(\\d+)",
    ],
  },
  // ApplePodcast — ApplePodcast (apple_podcast.py)
  {
    idType: "ApplePodcast",
    siteName: "ApplePodcast",
    patterns: [
      "https://[^.]+.apple.com/\\w+/podcast/*[^/?]*/id(\\d+)",
    ],
  },
  // Bandcamp — Bandcamp (bandcamp.py)
  {
    idType: "Bandcamp",
    siteName: "Bandcamp",
    patterns: [
      "https://([a-z0-9\\-]+.bandcamp.com/album/[^?#/]+).*",
    ],
    fallbackPatterns: [
      "https://([a-z0-9\\-\\.]+/album/[^?#/]+).*",
    ],
  },
  // Bangumi — Bangumi (bangumi.py)
  {
    idType: "Bangumi",
    siteName: "Bangumi",
    patterns: [
      "https://bgm\\.tv/subject/(\\d+)",
      "https://bangumi\\.tv/subject/(\\d+)",
      "https://chii\\.in/subject/(\\d+)",
    ],
  },
  // BoardGameGeek — BGG (bgg.py)
  {
    idType: "BGG",
    siteName: "BGG",
    patterns: [
      "^\\w+://boardgamegeek\\.com/boardgame/(\\d+)",
      "^\\w+://boardgamegeek\\.com/boardgameexpansion/(\\d+)",
    ],
  },
  // BibliotekDK_Edition — BibliotekDK (bibliotek_dk.py)
  {
    idType: "BibliotekDK_Edition",
    siteName: "BibliotekDK",
    patterns: [
      "https://bibliotek.dk/work/pid/([^?]+)",
    ],
  },
  // BibliotekDK_Work — BibliotekDK (bibliotek_dk.py)
  {
    idType: "BibliotekDK_Work",
    siteName: "BibliotekDK",
    patterns: [
      "https://bibliotek.dk/materiale/[^/]+/(work-of[^?/]+)",
    ],
  },
  // BnF — BnF (bnf.py)
  {
    idType: "BnF",
    siteName: "BnF",
    patterns: [
      "\\w+://catalogue\\.bnf\\.fr/ark:/12148/(cb\\d{8}[0-9a-z])",
    ],
  },
  // BooksTW — BooksTW (bookstw.py)
  {
    idType: "BooksTW",
    siteName: "BooksTW",
    patterns: [
      "\\w+://www\\.books\\.com\\.tw/products/(\\w+)",
    ],
  },
  // DiscogsRelease — Discogs (discogs.py)
  {
    idType: "Discogs_Release",
    siteName: "Discogs",
    patterns: [
      "https://www\\.discogs\\.com/release/(\\d+)[^\\d]*",
      "https://www\\.discogs\\.com/[a-z]{2}/release/(\\d+)[^\\d]*",
      "https://www\\.discogs\\.com/[a-z]{2}_[A-Z]{2}/release/(\\d+)[^\\d]*",
    ],
  },
  // DiscogsMaster — Discogs (discogs.py)
  {
    idType: "Discogs_Master",
    siteName: "Discogs",
    patterns: [
      "^https://www\\.discogs\\.com/master/(\\d+)[^\\d]*",
      "^https://www\\.discogs\\.com/[\\w\\-]+/master/(\\d+)[^\\d]*",
    ],
  },
  // DoubanBook — Douban (douban_book.py)
  {
    idType: "DoubanBook",
    siteName: "Douban",
    patterns: [
      "\\w+://book\\.douban\\.com/subject/(\\d+)/{0,1}",
      "\\w+://m.douban.com/book/subject/(\\d+)/{0,1}",
      "\\w+://www.douban.com/doubanapp/dispatch\\?uri=/book/(\\d+)/",
      "\\w+://www.douban.com/doubanapp/dispatch/book/(\\d+)",
    ],
  },
  // DoubanDrama — Douban (douban_drama.py)
  {
    idType: "DoubanDrama",
    siteName: "Douban",
    patterns: [
      "\\w+://www.douban.com/location/drama/(\\d+)/[^#]*$",
      "\\w+://www.douban.com/doubanapp/dispatch\\?uri=/drama/(\\d+)/",
      "\\w+://www.douban.com/doubanapp/dispatch/drama/(\\d+)",
    ],
  },
  // DoubanGame — Douban (douban_game.py)
  {
    idType: "DoubanGame",
    siteName: "Douban",
    patterns: [
      "\\w+://www\\.douban\\.com/game/(\\d+)/{0,1}",
      "\\w+://m.douban.com/game/subject/(\\d+)/{0,1}",
      "\\w+://www.douban.com/doubanapp/dispatch\\?uri=/game/(\\d+)/",
      "\\w+://www.douban.com/doubanapp/dispatch/game/(\\d+)",
    ],
  },
  // DoubanMovie — Douban (douban_movie.py)
  {
    idType: "DoubanMovie",
    siteName: "Douban",
    patterns: [
      "\\w+://movie\\.douban\\.com/subject/(\\d+)/{0,1}",
      "\\w+://m.douban.com/movie/subject/(\\d+)/{0,1}",
      "\\w+://www.douban.com/doubanapp/dispatch\\?uri=/movie/(\\d+)/",
      "\\w+://www.douban.com/doubanapp/dispatch/movie/(\\d+)",
    ],
  },
  // DoubanMusic — Douban (douban_music.py)
  {
    idType: "DoubanMusic",
    siteName: "Douban",
    patterns: [
      "\\w+://music\\.douban\\.com/subject/(\\d+)/{0,1}",
      "\\w+://m.douban.com/music/subject/(\\d+)/{0,1}",
      "\\w+://www.douban.com/doubanapp/dispatch\\?uri=/music/(\\d+)/",
      "\\w+://www.douban.com/doubanapp/dispatch/music/(\\d+)",
    ],
  },
  // DoubanPersonage — Douban (douban_personage.py)
  {
    idType: "DoubanPersonage",
    siteName: "Douban",
    patterns: [
      "\\w+://www\\.douban\\.com/personage/(\\d+)",
    ],
  },
  // FediverseInstance — Fediverse (fedi.py)
  {
    idType: "Fediverse",
    siteName: "Fediverse",
    patterns: [],
  },
  // Goodreads — Goodreads (goodreads.py)
  {
    idType: "Goodreads",
    siteName: "Goodreads",
    patterns: [
      ".+goodreads\\.com/.*book/show/(\\d+)",
      ".+goodreads\\.com/.*book/(\\d+)",
    ],
  },
  // GoogleBooks — GoogleBooks (google_books.py)
  {
    idType: "GoogleBooks",
    siteName: "GoogleBooks",
    patterns: [
      "https?://(?:books|www)\\.google\\.(?:com|cat|[a-z]{2}|(?:com|co)\\.[a-z]{2})/books/?\\?(?:(?!id=)[^&#]*&)*id=([A-Za-z0-9_-]+)(?:&(?!id=)[^&#]*)*(?:#.*)?$",
      "https?://(?:books|www)\\.google\\.(?:com|cat|[a-z]{2}|(?:com|co)\\.[a-z]{2})/books/about/[^/?#]+\\?(?:(?!id=)[^&#]*&)*id=([A-Za-z0-9_-]+)(?:&(?!id=)[^&#]*)*(?:#.*)?$",
      "https?://(?:books|www)\\.google\\.(?:com|cat|[a-z]{2}|(?:com|co)\\.[a-z]{2})/books/edition/[^/?#]+/([A-Za-z0-9_-]+)/?(?:[?#].*)?$",
      "https?://play\\.google\\.com/(?:store/books/details(?:/[^/?#]+)?/?|books/reader/?)\\?(?:(?!id=)[^&#]*&)*id=([A-Za-z0-9_-]+)(?:&(?!id=)[^&#]*)*(?:#.*)?$",
    ],
  },
  // IGDB — IGDB (igdb.py)
  {
    idType: "IGDB",
    siteName: "IGDB",
    patterns: [
      "\\w+://www\\.igdb\\.com/games/([a-zA-Z0-9\\-_]+)",
      "\\w+://m\\.igdb\\.com/games/([a-zA-Z0-9\\-_]+)",
    ],
  },
  // IMDB — IMDB (imdb.py)
  {
    idType: "IMDB",
    siteName: "IMDB",
    patterns: [
      "\\w+://www.imdb.com/title/(tt\\d+)",
      "\\w+://m.imdb.com/title/(tt\\d+)",
      "\\w+://www.imdb.com/name/(nm\\d+)",
      "\\w+://m.imdb.com/name/(nm\\d+)",
    ],
  },
  // Itch — Itch (itch.py)
  {
    idType: "Itch",
    siteName: "Itch",
    patterns: [
      "^https?://itch\\.io/embed/(\\d+).*",
    ],
  },
  // JJWXC — JJWXC (jjwxc.py)
  {
    idType: "JJWXC",
    siteName: "JJWXC",
    patterns: [
      "https://www\\.jjwxc\\.net/onebook\\.php\\?novelid=(\\d+)",
    ],
  },
  // MangaUpdates — MangaUpdates (mangaupdates.py)
  {
    idType: "MangaUpdates",
    siteName: "MangaUpdates",
    patterns: [
      "\\w+://(?:www\\.)?mangaupdates\\.com/series/([0-9A-Za-z]+)",
    ],
  },
  // MobyGames — MobyGames (mobygames.py)
  {
    idType: "MobyGames",
    siteName: "MobyGames",
    patterns: [
      "\\w+://www\\.mobygames\\.com/game/(\\d+)[/\\w\\-]*",
    ],
  },
  // MusicBrainzReleaseGroup — MusicBrainz (musicbrainz.py)
  {
    idType: "MusicBrainz_ReleaseGroup",
    siteName: "MusicBrainz",
    patterns: [
      "^\\w+://musicbrainz\\.org/release-group/([a-f0-9\\-]{36}).*",
    ],
  },
  // MusicBrainzRelease — MusicBrainz (musicbrainz.py)
  {
    idType: "MusicBrainz_Release",
    siteName: "MusicBrainz",
    patterns: [
      "^\\w+://musicbrainz\\.org/release/([a-f0-9\\-]{36}).*",
    ],
  },
  // MyAnimeListAnime — MyAnimeList (myanimelist.py)
  {
    idType: "MAL_Anime",
    siteName: "MyAnimeList",
    patterns: [
      "\\w+://myanimelist\\.net/anime/(\\d+)",
      "\\w+://myanimelist\\.net/anime\\.php\\?id=(\\d+)",
    ],
  },
  // MyAnimeListManga — MyAnimeList (myanimelist.py)
  {
    idType: "MAL_Manga",
    siteName: "MyAnimeList",
    patterns: [
      "\\w+://myanimelist\\.net/manga/(\\d+)",
      "\\w+://myanimelist\\.net/manga\\.php\\?id=(\\d+)",
    ],
  },
  // OpenLibrary — OpenLibrary (openlibrary.py)
  {
    idType: "OpenLibrary",
    siteName: "OpenLibrary",
    patterns: [
      "https://openlibrary\\.org/books/([^/\\?]+M)",
      "https://www\\.openlibrary\\.org/books/([^/\\?]+M)",
    ],
  },
  // OpenLibrary_Work — OpenLibrary (openlibrary.py)
  {
    idType: "OpenLibrary_Work",
    siteName: "OpenLibrary",
    patterns: [
      "https://openlibrary\\.org/works/([^/\\?]+W)",
      "https://www\\.openlibrary\\.org/works/([^/\\?]+W)",
    ],
  },
  // Qidian — Qidian (qidian.py)
  {
    idType: "Qidian",
    siteName: "Qidian",
    patterns: [
      "https://www\\.qidian\\.com/book/(\\d+)",
      "https://book\\.qidian\\.com/info/(\\d+)",
    ],
  },
  // RateYourMusic — RateYourMusic (rateyourmusic.py)
  {
    idType: "RateYourMusic_Release",
    siteName: "RateYourMusic",
    patterns: [
      "^https?://rateyourmusic\\.com/(release/(?:album|ep|single|comp|mixtape|video|djmix|bootleg|unauth)/[^/?#]+/[^/?#]+)/?",
      "^https?://www\\.rateyourmusic\\.com/(release/(?:album|ep|single|comp|mixtape|video|djmix|bootleg|unauth)/[^/?#]+/[^/?#]+)/?",
    ],
  },
  // Readmoo — Readmoo (readmoo.py)
  {
    idType: "Readmoo",
    siteName: "Readmoo",
    patterns: [
      "\\w+://(?:www\\.|m\\.)?readmoo\\.com/book/(\\d+)",
    ],
  },
  // RSS — RSS (rss.py)
  {
    idType: "RSS",
    siteName: "RSS",
    patterns: [
      ".+[./](rss|xml)",
    ],
  },
  // Spotify — Spotify (spotify.py)
  {
    idType: "Spotify_Album",
    siteName: "Spotify",
    patterns: [
      "^\\w+://open\\.spotify\\.com/album/([a-zA-Z0-9]+).*",
      "^\\w+://open\\.spotify\\.com/[\\w\\-]+/album/([a-zA-Z0-9]+).*",
    ],
  },
  // Steam — Steam (steam.py)
  {
    idType: "Steam",
    siteName: "Steam",
    patterns: [
      "\\w+://store\\.steampowered\\.com/app/(\\d+)",
    ],
  },
  // StoryGraph — StoryGraph (storygraph.py)
  {
    idType: "StoryGraph",
    siteName: "StoryGraph",
    patterns: [
      "https?://app\\.thestorygraph\\.com/books/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})",
    ],
  },
  // TMDB_Movie — TMDB (tmdb.py)
  {
    idType: "TMDB_Movie",
    siteName: "TMDB",
    patterns: [
      "^\\w+://www.themoviedb.org/movie/(\\d+)",
    ],
  },
  // TVDB_Series — TVDB (tvdb.py)
  {
    idType: "TVDB_Series",
    siteName: "TVDB",
    patterns: [
      "^https?://(?:www\\.)?thetvdb\\.com/dereferrer/series/(\\d+)",
      "^https?://(?:www\\.)?thetvdb\\.com/(?:index\\.php)?\\?tab=series&id=(\\d+)",
    ],
    fallbackPatterns: [
      "^https?://(?:www\\.)?thetvdb\\.com/series/([^/?#]+)/?(?:[?#].*)?$",
    ],
  },
  // TVDB_Movie — TVDB (tvdb.py)
  {
    idType: "TVDB_Movie",
    siteName: "TVDB",
    patterns: [
      "^https?://(?:www\\.)?thetvdb\\.com/dereferrer/movie/(\\d+)",
    ],
    fallbackPatterns: [
      "^https?://(?:www\\.)?thetvdb\\.com/movies/([^/?#]+)/?(?:[?#].*)?$",
    ],
  },
  // WikiData — WikiData (wikidata.py)
  {
    idType: "WikiData",
    siteName: "WikiData",
    patterns: [
      "^\\w+://www\\.wikidata\\.org/wiki/(Q\\d+)",
      "^\\w+://www\\.wikidata\\.org/entity/(Q\\d+)",
    ],
  },
  // WorldCat — WorldCat (worldcat.py)
  {
    idType: "OCLC",
    siteName: "WorldCat",
    patterns: [
      "https://search\\.worldcat\\.org/title/.+/oclc/(\\d+)",
      "https://search\\.worldcat\\.org/oclc/(\\d+)",
      "https://search\\.worldcat\\.org/title/(\\d+)",
      "https://search\\.worldcat\\.org/[a-zA-Z]+/title/(\\d+)",
      "https://www\\.worldcat\\.org/title/(\\d+)",
      "https://www\\.worldcat\\.org/oclc/(\\d+)",
    ],
  },
  // YouTubeMusic — YouTubeMusic (youtube_music.py)
  {
    idType: "YouTubeMusic",
    siteName: "YouTubeMusic",
    patterns: [
      "https://music\\.youtube\\.com/playlist\\?list=(OLAK5uy_[a-zA-Z0-9_-]+)",
    ],
  },
  // Ypshuo — Ypshuo (ypshuo.py)
  {
    idType: "Ypshuo",
    siteName: "Ypshuo",
    patterns: [
      "https://www\\.ypshuo\\.com/novel/(\\d+)\\.html",
    ],
  },
];
