/**
 * Regenerate `src/lib/catalog-sites.generated.ts` from NeoDB's source.
 *
 *   npm run catalog-sites:generate                    # pinned ref, fetched
 *   npm run catalog-sites:generate -- --ref <ref>     # another ref
 *   npm run catalog-sites:generate -- --source ~/src/neodb
 *
 * The table is what NeoDB itself uses to decide whether a pasted URL belongs to
 * a supported site, so our search box can make the same call without a round
 * trip. Run `npm run catalog-sites:check` afterwards.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import {
  describeSource,
  extractSites,
  parseSitePackageArgs,
  resolveSitesDir,
  type ExtractedSite,
} from "./upstream.ts";

const OUTPUT = path.join(
  import.meta.dirname,
  "../../src/lib/catalog-sites.generated.ts",
);

/** Python re syntax that would not mean the same thing in JavaScript. */
const UNTRANSLATABLE = [
  String.raw`(?P=`,
  String.raw`\A`,
  String.raw`\Z`,
  `(?i`,
  `(?m`,
  `(?s`,
];

/** Mirrors the anchoring of Python's `re.match`, which only pins the start. */
function normalizePatterns(patterns: string[], site: ExtractedSite) {
  return patterns.map((pattern) => {
    for (const token of UNTRANSLATABLE) {
      if (pattern.includes(token)) {
        throw new Error(
          `${site.className}: pattern uses ${token}, which needs a deliberate translation: ${pattern}`,
        );
      }
    }

    const normalized = pattern.replaceAll("(?P<", "(?<");

    new RegExp(`^(?:${normalized})`);

    return normalized;
  });
}

function renderList(patterns: string[], indent: string) {
  if (patterns.length === 0) {
    return "[]";
  }

  return [
    "[",
    ...patterns.map((pattern) => `${indent}  ${JSON.stringify(pattern)},`),
    `${indent}]`,
  ].join("\n");
}

function render(sites: ExtractedSite[], upstream: string) {
  const patternCount = sites.reduce(
    (total, site) => total + site.patterns.length + site.fallbackPatterns.length,
    0,
  );
  const rules = sites
    .map((site) => {
      const patterns = normalizePatterns(site.patterns, site);
      const fallbackPatterns = normalizePatterns(site.fallbackPatterns, site);

      return [
        `  // ${site.className} — ${site.siteName} (${site.module}.py)`,
        `  {`,
        `    idType: ${JSON.stringify(site.idType)},`,
        `    siteName: ${JSON.stringify(site.siteName)},`,
        `    patterns: ${renderList(patterns, "    ")},`,
        ...(fallbackPatterns.length
          ? [`    fallbackPatterns: ${renderList(fallbackPatterns, "    ")},`]
          : []),
        `  },`,
      ].join("\n");
    })
    .join("\n");

  return `// Generated by \`npm run catalog-sites:generate\`. Do not edit by hand.
//
// Upstream: ${upstream} — neodb/catalog/sites/
// ${sites.length} sites, ${patternCount} patterns, in NeoDB's registration order:
// the first site whose pattern matches a URL is the one that handles it.
//
// \`patterns\` are the site's URL_PATTERNS. \`fallbackPatterns\` are the
// pattern-shaped part of what the sites that override \`validate_url_fallback\`
// start from; NeoDB only consults those when no site matched above.

export type CatalogSiteRule = {
  idType: string;
  siteName: string;
  patterns: string[];
  fallbackPatterns?: string[];
};

export const CATALOG_SITE_RULES: CatalogSiteRule[] = [
${rules}
];
`;
}

const source = parseSitePackageArgs();
const sitesDir = await resolveSitesDir(source);
const upstream = describeSource(source);
const sites = extractSites(sitesDir);

await writeFile(OUTPUT, render(sites, upstream));

const withoutPatterns = sites
  .filter((site) => site.patterns.length === 0)
  .map((site) => site.className);

console.log(
  `wrote ${path.relative(process.cwd(), OUTPUT)}: ${sites.length} sites from ${upstream}`,
);
console.log(
  withoutPatterns.length
    ? `no primary pattern (fallback-only upstream): ${withoutPatterns.join(", ")}`
    : "every site has a primary pattern",
);
